/* 테이블 삭제
DROP TABLE USERS;
DROP TABLE COMPANY;
DROP TABLE DEPT;
DROP TABLE PROJECT;
DROP TABLE PROJECT_MEMBER;
DROP TABLE PROJECT_DEPT;
DROP TABLE FILES;
DROP TABLE COMMUTE;
DROP TABLE DAYOFF;
DROP TABLE ALERT;
DROP TABLE BOARDALL;
DROP TABLE SCHEDULE;
DROP TABLE TODO
DROP TABLE TODOCONTENT;
DROP TABLE VOTE;
DROP TABLE TASK;
DROP TABLE COMMONBOARD;
DROP TABLE STORAGE;
DROP TABLE LIKE;
DROP TABLE REPLY;
DROP TABLE CHAT;
DROP TABLE CHATMEMBER;
DROP TABLE CHATCONTENT;
DROP TABLE CHATALERT;
*/


--1. 사용자 테이블
CREATE TABLE USERS(
UNO VARCHAR2(20) NOT NULL PRIMARY KEY,
CNO VARCHAR2(20) NOT NULL,
DNO VARCHAR2(20),
UEMAIL VARCHAR2(50) NOT NULL,
UNAME VARCHAR2(20) NOT NULL,
UTELL VARCHAR2(15),
UPWD VARCHAR2(100) NOT NULL,
URANK VARCHAR2(20) DEFAULT '사원' NOT NULL,
USTATE NUMBER(1) DEFAULT 1,
UFILENAME VARCHAR2(500),
UFILEPATH VARCHAR2(500),
UAUTHORITY VARCHAR2(20) DEFAULT 'ROLE_USER' NOT NULL,
ENABLED NUMBER(1) NOT NULL,
FAILURE_CNT NUMBER(2)  DEFAULT 0, 

CONSTRAINT FK_CNO_USERS FOREIGN KEY(CNO) REFERENCES COMPANY(CNO) ON DELETE CASCADE,
CONSTRAINT FK_DNO_USERS FOREIGN KEY(DNO) REFERENCES DEPT(DNO) ON DELETE CASCADE
);

CREATE SEQUENCE UNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE USERS IS '사용자 테이블';
COMMENT ON COLUMN USERS.UNO IS '사원번호';
COMMENT ON COLUMN USERS.CNO IS '회사번호';
COMMENT ON COLUMN USERS.DNO IS '부서번호';
COMMENT ON COLUMN USERS.UEMAIL IS '이메일';
COMMENT ON COLUMN USERS.UNAME IS '이름';
COMMENT ON COLUMN USERS.UTELL IS '연락처';
COMMENT ON COLUMN USERS.UPWD IS '비밀번호';
COMMENT ON COLUMN USERS.URANK IS '직급';
COMMENT ON COLUMN USERS.USTATE IS '재직상태';
COMMENT ON COLUMN USERS.UFILENAME IS '프로필사진파일명';
COMMENT ON COLUMN USERS.UFILEPATH IS '프로필사진경로';
COMMENT ON COLUMN USERS.UAUTHORITY IS '권한타입';
COMMENT ON COLUMN USERS.ENABLED IS '계정사용여부';
COMMENT ON COLUMN USERS.FAILURE_CNT IS '로그인실패횟수';


--2. 회사 테이블
CREATE TABLE COMPANY(
CNO VARCHAR2(20) NOT NULL PRIMARY KEY,
CNAME VARCHAR(100) NOT NULL,
CEO VARCHAR2(20) NOT NULL,
CTEL VARCHAR2(15),
CURL VARCHAR2(50) NOT NULL,
CLOGO VARCHAR2(300),
CLOGOPATH VARCHAR2(500),
CCATE VARCHAR2(20) NOT NULL
);
CREATE SEQUENCE CNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE COMPANY IS '회사 테이블';
COMMENT ON COLUMN COMPANY.CNO IS '회사번호';
COMMENT ON COLUMN COMPANY.CNAME IS '회사명';
COMMENT ON COLUMN COMPANY.CEO IS '대표자';
COMMENT ON COLUMN COMPANY.CTEL IS '연락처';
COMMENT ON COLUMN COMPANY.CURL IS '회사URL';
COMMENT ON COLUMN COMPANY.CLOGO IS '회사로고';
COMMENT ON COLUMN COMPANY.CLOGOPATH IS '회사로고경로';
COMMENT ON COLUMN COMPANY.CCATE IS '회사직종';


--3. 부서 테이블
CREATE TABLE DEPT(
DNO VARCHAR2(20) NOT NULL PRIMARY KEY,
CNO VARCHAR2(20) NOT NULL,
DNAME VARCHAR2(50) NOT NULL,
CONSTRAINT FK_CNO_DEPT FOREIGN KEY(CNO) REFERENCES COMPANY(CNO)
);

CREATE SEQUENCE DNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE DEPT IS '부서 테이블';
COMMENT ON COLUMN DEPT.DNO IS '부서번호';
COMMENT ON COLUMN DEPT.CNO IS '회사번호';
COMMENT ON COLUMN DEPT.DNAME IS '부서명';


--4. 프로젝트 테이블
CREATE TABLE PROJECT(
PNO VARCHAR2(20) NOT NULL PRIMARY KEY,
PNAME VARCHAR2(50) NOT NULL,
PDESC VARCHAR2(300),
PDATE DATE DEFAULT SYSDATE,
POPEN NUMBER(1) DEFAULT 1
);

CREATE SEQUENCE PNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE PROJECT IS '프로젝트 테이블';
COMMENT ON COLUMN PROJECT.PNO IS '프로젝트 번호';
COMMENT ON COLUMN PROJECT.PNAME IS '프로젝트명';
COMMENT ON COLUMN PROJECT.PDESC IS '프로젝트 설명';
COMMENT ON COLUMN PROJECT.PDATE IS '프로젝트 개설일';
COMMENT ON COLUMN PROJECT.POPEN IS '공개여부';


--5. 프로젝트 멤버 테이블
CREATE TABLE PROJECT_MEMBER(
    PNO VARCHAR2(20) NOT NULL,
    UNO VARCHAR2(20),
    PADMIN NUMBER,
    CONSTRAINT FK_PNO_PJM FOREIGN KEY(PNO) REFERENCES PROJECT(PNO),
    CONSTRAINT FK_DNO_PJM FOREIGN KEY(DNO) REFERENCES DEPT(DNO)
);

COMMENT ON TABLE PROJECT_MEMBER IS '프로젝트 멤버 테이블';
COMMENT ON COLUMN PROJECT_MEMBER.PNO IS '프로젝트 번호';
COMMENT ON COLUMN PROJECT_MEMBER.UNO IS '사원번호';
COMMENT ON COLUMN PROJECT_MEMBER.PADMIN IS '프로젝트 관리자타입';
--padmin : 1 관리자 0 일반 


--6. 프로젝트 부서 테이블
CREATE TABLE PROJECT_DEPT(
    PNO VARCHAR2(20) NOT NULL,
    DNO VARCHAR2(20),
    CONSTRAINT FK_PNO_PJD FOREIGN KEY(PNO) REFERENCES PROJECT(PNO),
    CONSTRAINT FK_DNO_PJD FOREIGN KEY(DNO) REFERENCES DEPT(DNO)
);

COMMENT ON TABLE  PROJECT_DEPT IS '프로젝트 부서 테이블';
COMMENT ON COLUMN PROJECT_DEPT.PNO IS '프로젝트 번호';
COMMENT ON COLUMN PROJECT_DEPT.DNO IS '프로젝트 부서';


--7. 파일 테이블
CREATE TABLE FILES(
FNAME VARCHAR2(500) NOT NULL PRIMARY KEY,
PNO VARCHAR2(20) NOT NULL,
BNO NUMBER(20) NOT NULL,
UNO VARCHAR2(50) NOT NULL,
FDATE DATE DEFAULT SYSDATE,
FSIZE VARCHAR2(50),
FPATH VARCHAR2(300),
IMGSRC VARCHAR2(300),
FORIGINALNAME VARCHAR2(300),

CONSTRAINT FK_PNO_FILES FOREIGN KEY(PNO) REFERENCES PROJECT(PNO) ON DELETE CASCADE,
CONSTRAINT FK_UNO_FILES FOREIGN KEY(UNO) REFERENCES USERS(UNO) ON DELETE CASCADE,
CONSTRAINT FK_BNO_FILES FOREIGN KEY(BNO) REFERENCES BOARDALL(BNO) ON DELETE CASCADE
);

COMMENT ON TABLE FILES IS '파일';
COMMENT ON COLUMN FILES.FNAME IS '파일명';
COMMENT ON COLUMN FILES.PNO IS '프로젝트번호';
COMMENT ON COLUMN FILES.BNO IS '글번호';
COMMENT ON COLUMN FILES.UNO IS '사원번호';
COMMENT ON COLUMN FILES.FDATE IS '파일업로드일자';
COMMENT ON COLUMN FILES.FSIZE IS '파일크기';
COMMENT ON COLUMN FILES.FPATH IS '파일경로';
COMMENT ON COLUMN FILES.IMGSRC IS '이미지경로';
COMMENT ON COLUMN FILES.FORIGINALNAME IS '파일원본이름';


--8. 출퇴근 테이블
CREATE TABLE COMMUTE(
UNO VARCHAR2(20) NOT NULL,
CDATE DATE DEFAULT SYSDATE NOT NULL,
CSTATE NUMBER(1) NOT NULL,
CSTARTTIME VARCHAR2(20),
CENDTIME VARCHAR2(20),
CWORKTIME NUMBER(5,2),
CREASON VARCHAR2(200),
CONSTRAINT FK_UNO_COM FOREIGN KEY (UNO) REFERENCES USERS
ON DELETE CASCADE
);

COMMENT ON COLUMN COMMUTE.UNO IS '사원번호';
COMMENT ON COLUMN COMMUTE.CDATE IS '등록일자';
COMMENT ON COLUMN COMMUTE.CSTATE IS '출근상태';
COMMENT ON COLUMN COMMUTE.CSTARTTIME IS '출근시간';
COMMENT ON COLUMN COMMUTE.CENDTIME IS '퇴근시간';
COMMENT ON COLUMN COMMUTE.CWORKTIME IS '근무시간';
COMMENT ON COLUMN COMMUTE.CREASON IS '사유';

/*CSTATE 
0 : 정상출근
1 : 지각
2 : 기타(누락, 오류 등)*/


--9. 시간외 근무 테이블
CREATE TABLE OVERWORK(
OWNO VARCHAR2(20) NOT NULL PRIMARY KEY,
UNO VARCHAR2(20) NOT NULL,
OWDATE DATE NOT NULL,
OWTIME NUMBER(2) NOT NULL,
OWTITLE VARCHAR2(200) NOT NULL,
OWREASON VARCHAR2(600) NOT NULL,
OWAPPROVAL NUMBER(1),
OWAPPLYDATE DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT FK_UNO_OVER FOREIGN KEY (UNO) REFERENCES USERS
ON DELETE CASCADE
)
 CREATE SEQUENCE OWNO_SE INCREMENT BY 1 START WITH 1;
COMMENT ON COLUMN OVERWORK.OWNO IS '신청글번호';
COMMENT ON COLUMN OVERWORK.UNO IS '사원번호';
COMMENT ON COLUMN OVERWORK.OWDATE IS '시간외근무예정일';
COMMENT ON COLUMN OVERWORK.OWTIME IS '예상시간';
COMMENT ON COLUMN OVERWORK.OWTITLE IS '업무명';
COMMENT ON COLUMN OVERWORK.OWREASON IS '사유';
COMMENT ON COLUMN OVERWORK.OWAPPROVAL IS '승인여부';
COMMENT ON COLUMN OVERWORK.OWAPPLYDATE IS '신청날짜';

--10. 휴가 테이블
CREATE TABLE DAYOFF(
DFNO VARCHAR2(20) NOT NULL PRIMARY KEY,
UNO VARCHAR2(20) NOT NULL,
OFFDAYS NUMBER(2) NOT NULL,
OFFSTART DATE NOT NULL,
OFFEND DATE NOT NULL,
OFFREASON VARCHAR2(200),
OFFTIME DATE DEFAULT SYSDATE NOT NULL,
OFFAPPROVAL NUMBER(1) DEFAULT 0,
CONSTRAINT FK_UNO_DO FOREIGN KEY (UNO) REFERENCES USERS
ON DELETE CASCADE
);
CREATE SEQUENCE DFNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON COLUMN DAYOFF.DFNO IS '신청글번호';
COMMENT ON COLUMN DAYOFF.UNO IS '사원번호';
COMMENT ON COLUMN DAYOFF.OFFDAYS IS '휴가일수';
COMMENT ON COLUMN DAYOFF.OFFSTART IS '휴가시작일';
COMMENT ON COLUMN DAYOFF.OFFEND IS '휴가마지막일';
COMMENT ON COLUMN DAYOFF.OFFTIME IS '휴가신청일';
COMMENT ON COLUMN DAYOFF.OFFAPPROVAL IS '휴가승인여부';


--11. 전자결재 테이블
CREATE TABLE APPROVAL(
APNO VARCHAR2(20) NOT NULL PRIMARY KEY,
DNO VARCHAR2(20) NOT NULL,
UNO VARCHAR2(20) NOT NULL,
APTITLE VARCHAR2(50) NOT NULL,
APDATE DATE DEFAULT SYSDATE,
APCONTENT VARCHAR2(1800),
APPERSON VARCHAR2(20),
APSTATE NUMBER(2) default '0' NOT NULL,
APREJECTION VARCHAR2(50),
APPLACE VARCHAR2(50),
APATTEND VARCHAR(50),
APDEC VARCHAR2(100),
APETC VARCHAR2(100),
APFORMAT VARCHAR2(50),
APDRAFTER VARCHAR2(50),
APPTITLE VARCHAR2(50) NOT NULL,

CONSTRAINT FK_DNO_AP FOREIGN KEY(DNO) REFERENCES DEPT(DNO),
CONSTRAINT FK_UNO_AP FOREIGN KEY(UNO) REFERENCES USERS(UNO)
);

CREATE SEQUENCE APNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE APPROVAL IS '전자결재';
COMMENT ON COLUMN APPROVAL.APNO IS '전자결재번호';
COMMENT ON COLUMN APPROVAL.DNO IS '부서번호';
COMMENT ON COLUMN APPROVAL.UNO IS '기안자사원번호';
COMMENT ON COLUMN APPROVAL.APTITLE IS '기안제목';
COMMENT ON COLUMN APPROVAL.APDATE IS '기안작성일자';
COMMENT ON COLUMN APPROVAL.APCONTENT IS '기안내용';
COMMENT ON COLUMN APPROVAL.APPERSON IS '결재자';
COMMENT ON COLUMN APPROVAL.APSTATE IS '결재상태';
COMMENT ON COLUMN APPROVAL.APREJECTION IS '반려사유';
COMMENT ON COLUMN APPROVAL.APPLACE IS '장소';
COMMENT ON COLUMN APPROVAL.APATTEND IS '참석자';
COMMENT ON COLUMN APPROVAL.APDEC IS '결정사항';
COMMENT ON COLUMN APPROVAL.APETC IS '기타';
COMMENT ON COLUMN APPROVAL.APFORMAT IS '문서형식';
COMMENT ON COLUMN APPROVAL.APDRAFTER IS '기안자';
COMMENT ON COLUMN APPROVAL.APPTITLE IS '프로젝트제목';


--12. 알림 테이블
CREATE TABLE ALERT(
RNO VARCHAR2(20),
UNO VARCHAR2(20) NOT NULL,
PNO VARCHAR2(20),
BNO number(10),
ACOUNT NUMBER(1) NOT NULL,
ADATE DATE DEFAULT SYSDATE,
ACONTENT VARCHAR2(300),
CONSTRAINT FK_UNO_AL FOREIGN KEY (UNO) REFERENCES USERS,
CONSTRAINT FK_BNO_AL FOREIGN KEY (BNO) REFERENCES BOARDALL,
CONSTRAINT FK_RNO_AL FOREIGN KEY (RNO) REFERENCES REPLY,
CONSTRAINT FK_PNO_AL FOREIGN KEY (PNO) REFERENCES PROJECT
);

COMMENT ON TABLE ALERT IS '알림';
COMMENT ON COLUMN ALERT.RNO IS '댓글번호';
COMMENT ON COLUMN ALERT.UNO IS '사원번호';
COMMENT ON COLUMN ALERT.PNO IS '프로젝트번호';
COMMENT ON COLUMN ALERT.BNO IS '글번호';
COMMENT ON COLUMN ALERT.ACOUNT IS '미확인개수';
COMMENT ON COLUMN ALERT.ADATE IS '알림생성일';
COMMENT ON COLUMN ALERT.ACONTENT  IS '알림내용';


--13. 전체글 테이블
CREATE TABLE BOARDALL (
BNO NUMBER(10) NOT NULL PRIMARY KEY,
PNO VARCHAR2(20) NOT NULL,
UNO VARCHAR2(20) NOT NULL,
BNAME VARCHAR2(150) NOT NULL,
BOPEN NUMBER(1) NOT NULL,
BTYPE NUMBER(1) NOT NULL,
BFIRST NUMBER(1),
BDATE DATE DEFAULT SYSDATE,

CONSTRAINT FK_PNO_BA FOREIGN KEY(PNO) REFERENCES PROJECT(PNO),
CONSTRAINT FK_UNO_BA FOREIGN KEY(UNO) REFERENCES USERS(UNO)
);

CREATE SEQUENCE BNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE BOARDALL IS '글쓰기공통';
COMMENT ON COLUMN BOARDALL.BNO IS '글번호';
COMMENT ON COLUMN BOARDALL.PNO IS '프로젝트 번호';
COMMENT ON COLUMN BOARDALL.UNO IS '글쓴이';
COMMENT ON COLUMN BOARDALL.BNAME IS '제목';
COMMENT ON COLUMN BOARDALL.BOPEN IS '공개여부';
COMMENT ON COLUMN BOARDALL.BTYPE IS '글타입';
COMMENT ON COLUMN BOARDALL.BFIRST IS '상단글고정'; 
COMMENT ON COLUMN BOARDALL.BDATE IS '글작성시간';

/*상단글 고정 : 고정아님 0 / 고정 1
공개여부 : 전체공개 0 / 관리자만 공개 1 
글타입 : 일반글 1 / 업무 2 / 일정 3 / 할일 4 */

--13.2 전체글 VIEW (BOARDALL_VIEW) 생성 : BOARDALL + 글작성자(USERS)
CREATE OR REPLACE VIEW BOARDALL_VIEW AS
SELECT DISTINCT B.*, U.UNO, U.UNAME, UFILEPATH
FROM BOARDALL B INNER JOIN USERS U ON B.UNO = U.UNO;


--14. 일정 테이블
CREATE TABLE SCHEDULE(
BNO NUMBER(10) NOT NULL,
SSTART VARCHAR2(20) NOT NULL,
SEND VARCHAR2(20) NOT NULL,
SPLACE VARCHAR2(250),
SMEMO VARCHAR2(150),
ATTENDEE VARCHAR2(50)
CONSTRAINT FK_BNO_S FOREIGN KEY(BNO) REFERENCES BOARDALL(BNO) ON DELETE CASCADE;
);

COMMENT ON TABLE SCHEDULE IS '일정 테이블';
COMMENT ON COLUMN SCHEDULE.BNO IS '글번호';
COMMENT ON COLUMN SCHEDULE.SSTART IS '시작일시';
COMMENT ON COLUMN SCHEDULE.SEND IS '마감일시';
COMMENT ON COLUMN SCHEDULE.SPLACE IS '장소';
COMMENT ON COLUMN SCHEDULE.SMEMO IS '메모';
COMMENT ON COLUMN SCHEDULE.ATTENDEE IS '참석자';

--15.1  할일 테이블
CREATE TABLE TODO(
BNO NUMBER(10) NOT NULL,
TDCONTENT VARCHAR2(1800),
TDDATE VARCHAR2(10) NOT NULL,
TDCHECK NUMBER(1),
TDRESPONSIBILITY VARCHAR2(20) NOT NULL,
TDNO NUMBER(10) NOT NULL UNIQUE,
CONSTRAINT FK_BNO_TODO FOREIGN KEY(BNO) REFERENCES BOARDALL(BNO) ON DELETE CASCADE
);
CREATE SEQUENCE TDNO_SE INCREMENT BY 1 START WITH 1;

상단글 고정 : 할일 수행 1 / 비수행 0

COMMENT ON TABLE TODO IS '할일 테이블';
COMMENT ON COLUMN TODO.BNO IS '글번호';
COMMENT ON COLUMN TODO.TDCONTENT  IS '할일내용';
COMMENT ON COLUMN TODO.TDDATE IS '마감일';
COMMENT ON COLUMN TODO.TDCHECK  IS '할일여부체크';
COMMENT ON COLUMN TODO.TDRESPONSIBILITY IS '담당자';
COMMENT ON COLUMN TODO.TDNO  IS '할일글번호';

--15.2 할일 VIEW (TODO_VIEW) 생성 : TODO + 담당자이름 (USERS)
CREATE OR REPLACE VIEW TODO_VIEW AS
SELECT DISTINCT TD.*, U.UNO AS TDUNO, U.UNAME, U.UFILEPATH
FROM TODO TD
LEFT JOIN USERS U
ON TD.TDRESPONSIBILITY = U.UNO;


--16. 업무 테이블
CREATE TABLE TASK(
BNO NUMBER(10) NOT NULL,
TSTATE VARCHAR2(50) NOT NULL,
TSTART DATE NOT NULL,
TEND DATE NOT NULL,
TRATE VARCHAR2(50) NOT NULL,
TPRIORITY VARCHAR2(20) NOT NULL,
TMEMO VARCHAR2(1800),
TASKMANAGER VARCHAR2(20),
CONSTRAINT FK_BNO_TASK FOREIGN KEY(BNO) REFERENCES BOARDALL(BNO)
);

COMMENT ON TABLE TASK IS '업무 테이블';
COMMENT ON COLUMN TASK.BNO IS '글번호';
COMMENT ON COLUMN TASK.TSTATE IS '업무상태';
COMMENT ON COLUMN TASK.TSTART IS '시작일시';
COMMENT ON COLUMN TASK.TEND IS '마감일시';
COMMENT ON COLUMN TASK.TRATE IS '달성률';
COMMENT ON COLUMN TASK.TPRIORITY IS '우선순위';
COMMENT ON COLUMN TASK.TMEMO IS '글내용';
COMMENT ON COLUMN TASK.TASKMANAGER IS '담당자 사원번호';


--17. 일반글 테이블
CREATE TABLE COMMONBOARD(
BNO NUMBER(10) PRIMARY KEY,
BDESC VARCHAR2(1800) NOT NULL,
CONSTRAINT FK_BNO_COMMON FOREIGN KEY(BNO) REFERENCES  BOARDALL(BNO) ON DELETE CASCADE
);

COMMENT ON TABLE COMMONBOARD IS '일반글 테이블';
COMMENT ON COLUMN COMMONBOARD.BNO IS '글번호';
COMMENT ON COLUMN COMMONBOARD.BDESC IS '글내용';


--18. 댓글 테이블
CREATE TABLE REPLY(
RNO VARCHAR2(20) PRIMARY KEY,
UNO VARCHAR2(20) NOT NULL,
BNO NUMBER(10) NOT NULL,
PNO VARCHAR2(20) NOT NULL,
RDATE DATE NOT NULL,
RDESC VARCHAR2(1800) NOT NULL,
CONSTRAINT FK_UNO_REP FOREIGN KEY(UNO) REFERENCES USERS(UNO),
CONSTRAINT FK_BNO_REP FOREIGN KEY(BNO) REFERENCES BOARDALL(BNO),
CONSTRAINT FK_PNO_REP FOREIGN KEY(PNO) REFERENCES PROJECT(PNO)
);

CREATE SEQUENCE RNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE REPLY IS '댓글 테이블';
COMMENT ON COLUMN REPLY.RNO IS '댓글번호';
COMMENT ON COLUMN REPLY.UNO IS '사원번호';
COMMENT ON COLUMN REPLY.BNO IS '글번호';
COMMENT ON COLUMN REPLY.PNO IS '프로젝트 번호';
COMMENT ON COLUMN REPLY.RDATE IS '댓글 작성일';
COMMENT ON COLUMN REPLY.RDESC IS '댓글 내용';


--19. 채팅 테이블
CREATE TABLE CHAT(
CHATNO VARCHAR2(20) PRIMARY KEY,
PNO VARCHAR2(20),
CHATNAME VARCHAR2(50),
CONSTRAINT FK_PNO_CHAT FOREIGN KEY(PNO) REFERENCES PROJECT(PNO)
);

CREATE SEQUENCE CHATNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE CHAT IS '채팅 테이블';
COMMENT ON COLUMN CHAT.CHATNO IS '채팅방 번호';
COMMENT ON COLUMN CHAT.PNO IS '프로젝트 번호';
COMMENT ON COLUMN CHAT.CHATNAME IS '채팅방 제목';

--20. 채팅참여자 테이블
CREATE TABLE CHATMEMBER(
CHATNO VARCHAR2(20) NOT NULL,
UNO VARCHAR2(20) NOT NULL,
CREATCHAT NUMBER(2) NOT NULL,
CHATSTARTDATE DATE NOT NULL,
CHATENDDATE DATE,
CONSTRAINT FK_CHATNO_CM FOREIGN KEY(CHATNO) REFERENCES CHAT(CHATNO),
CONSTRAINT FK_UNO_CM FOREIGN KEY(UNO) REFERENCES USERS(UNO)
);

COMMENT ON TABLE CHATMEMBER IS '채팅참여자 테이블';
COMMENT ON COLUMN CHATMEMBER.CHATNO IS '채팅방 번호';
COMMENT ON COLUMN CHATMEMBER.UNO IS '사원 번호';
COMMENT ON COLUMN CHATMEMBER.CREATCHAT IS '개설자여부';
COMMENT ON COLUMN CHATMEMBER.CHATSTARTDATE IS '채팅참여일시';
COMMENT ON COLUMN CHATMEMBER.CHATENDDATE IS '채팅종료일시';

-- 개설자 여부 : 1 (개설자) 0 (미개설자)


--21. 채팅내용 테이블
CREATE TABLE CHATCONTENT(
CCNO NUMBER(20) PRIMARY KEY,
CHATNO VARCHAR2(20) NOT NULL,
UNO VARCHAR2(20) NOT NULL,
CHATDATE DATE NOT NULL,
CONTENT VARCHAR2(1800),
CHATFIX NUMBER(1),
CHATIMG VARCHAR2(50),
CHATFILEPATH VARCHAR2(300),
CONSTRAINT FK_CHATNO_CC FOREIGN KEY(CHATNO) REFERENCES CHAT(CHATNO),
CONSTRAINT FK_UNO_CC FOREIGN KEY(UNO) REFERENCES USERS(UNO)
);

CREATE SEQUENCE CCNO_SE INCREMENT BY 1 START WITH 1;

COMMENT ON TABLE CHATCONTENT IS '채팅내용 테이블';
COMMENT ON COLUMN CHATCONTENT.CCNO IS '채팅 대화순번';
COMMENT ON COLUMN CHATCONTENT.CHATNO IS '채팅방 번호';
COMMENT ON COLUMN CHATCONTENT.CHATDATE IS '사원 번호';
COMMENT ON COLUMN CHATCONTENT.CONTENT IS '대화내용';
COMMENT ON COLUMN CHATCONTENT.CHATFIX IS '고정글 여부';
COMMENT ON COLUMN CHATCONTENT.CHATIMG IS '채팅방 이미지';
COMMENT ON COLUMN CHATCONTENT.CHARFILEPATH IS '채팅방 이미지 경로';
 

--22. 채팅알림 테이블
CREATE TABLE CHATALERT(
CHATNO VARCHAR2(20) NOT NULL,
UNO VARCHAR2(20) NOT NULL,
CHATCOUNT NUMBER(20) NOT NULL,
CONSTRAINT FK_CHATNO_CA FOREIGN KEY(CHATNO) REFERENCES CHAT(CHATNO),
CONSTRAINT FK_UNO_CA FOREIGN KEY(UNO) REFERENCES USERS(UNO)
);

COMMENT ON TABLE CHATALERT IS '채팅알림 테이블';
COMMENT ON COLUMN CHATALERT.CHATNO IS '채팅방 번호';
COMMENT ON COLUMN CHATALERT.UNO IS '사원 번호';
COMMENT ON COLUMN CHATALERT.CHATCOUNT IS '미확인 채팅수';

--23. 자동로그인 테이블
CREATE TABLE PERSISTENT_LOGINS (
USERNAME VARCHAR(64) NOT NULL,
SERIES VARCHAR(64) NOT NULL,
TOKEN VARCHAR(64) NOT NULL,
LAST_USED TIMESTAMP NOT NULL,
PRIMARY KEY (SERIES)
);

COMMENT ON TABLE PERSISTENT_LOGINS IS '자동로그인 테이블';
COMMENT ON COLUMN PERSISTENT_LOGINS.USERNAME IS '유저 email';
COMMENT ON COLUMN PERSISTENT_LOGINS.SERIES IS '쿠키 고유값';
COMMENT ON COLUMN PERSISTENT_LOGINS.TOKEN IS '쿠키 인증값';
COMMENT ON COLUMN PERSISTENT_LOGINS.LAST_USED IS '최근 자동로그인 시간';

